# Numpy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[0:3]

array([0, 1, 2])

In [5]:
arr[4]

4

In [6]:
# From index 1 to 5
arr[1:5]

array([1, 2, 3, 4])

In [7]:
# Everything upto index 5 
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
# Start from index 6 to end
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
# Start from 5 to the end and go in steps of 2
arr[5::2]

array([5, 7, 9])

In [11]:
# Broadcasting
arr[::2] = 100
arr

array([100,   1, 100,   3, 100,   5, 100,   7, 100,   9, 100])

In [12]:
# Reset
a1 = np.arange(11)

In [13]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
# a2 can be consiered to be view into teh original a1 array
a2 = a1[0:6]

In [15]:
a2

array([0, 1, 2, 3, 4, 5])

In [16]:
a2[:] = 99

In [17]:
a2

array([99, 99, 99, 99, 99, 99])

In [18]:
a1

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
## ========

In [21]:
# Copies
a1x = a1.copy()

In [22]:
a1x

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
a1x[0:4] = 10

In [24]:
a1x

array([10, 10, 10, 10, 99, 99,  6,  7,  8,  9, 10])

In [25]:
a1

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
## ========

In [28]:
s2 = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [29]:
s2

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [32]:
s2[0][0]

5

In [33]:
s2[0,0]

5

In [34]:
s2[0]

array([ 5, 10, 15])

In [35]:
s2[2,1]

40

In [36]:
s2[2][1]

40

In [37]:
s2[:2, 1:]

array([[10, 15],
       [25, 30]])

In [40]:
s2[1:, 1:2]

array([[25],
       [40]])

In [41]:
s2[1:, 1]

array([25, 40])

In [42]:
s3 = np.random.randint(1,100,100).reshape(10,10)

In [43]:
s3

array([[13, 96, 78,  2, 23, 54, 84, 89, 50, 98],
       [24, 72, 32, 51, 93, 99, 30, 62, 24, 57],
       [67, 38, 81, 99, 85, 58, 44, 62, 49,  7],
       [38, 16, 70, 80, 87, 37, 29, 21, 85, 52],
       [95, 91, 92, 82,  3, 22, 38, 91, 36, 71],
       [47, 77, 75, 10, 81, 51, 36, 10, 16, 72],
       [10, 72, 11, 64, 74, 60, 25, 97, 87, 22],
       [14, 65, 37, 84, 85,  3, 11, 12, 13, 23],
       [91, 93, 90, 39, 45, 78, 10, 75, 88, 93],
       [31, 89, 24, 15, 21, 85, 33, 48, 17, 37]])

In [45]:
s3[5:,5:]

array([[51, 36, 10, 16, 72],
       [60, 25, 97, 87, 22],
       [ 3, 11, 12, 13, 23],
       [78, 10, 75, 88, 93],
       [85, 33, 48, 17, 37]])

In [46]:
s3[:5,5:]

array([[54, 84, 89, 50, 98],
       [99, 30, 62, 24, 57],
       [58, 44, 62, 49,  7],
       [37, 29, 21, 85, 52],
       [22, 38, 91, 36, 71]])

In [47]:
s3[:5,:5]

array([[13, 96, 78,  2, 23],
       [24, 72, 32, 51, 93],
       [67, 38, 81, 99, 85],
       [38, 16, 70, 80, 87],
       [95, 91, 92, 82,  3]])

In [48]:
# Conditional selection

In [49]:
a = np.arange(11)

In [50]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [52]:
# array with condition returns boolean array
ba = a > 5

In [53]:
# Boolean array can be used to select elements that match criteria
a[ba]

array([ 6,  7,  8,  9, 10])

In [54]:
# Combine
a[a > 5]

array([ 6,  7,  8,  9, 10])

In [55]:
a[a < 3]

array([0, 1, 2])