# NumPy Arrays

In [1]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [7]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# Numpy built in methods

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [12]:
np.zeros(4)

array([0., 0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
# Generate ones as a 1d array
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
# 2d array of ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
# Linspace -> Evenly spaces points from start to finish
np.linspace(0,10,9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [21]:
#Identity matrix -> 2d square matrix with ones as diagonal 
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
# Random
# Uniformley distributed from 0 to 1 
np.random.rand(4)

array([0.1359815 , 0.04420359, 0.30778795, 0.37095823])

In [24]:
np.random.rand(5,5)

array([[0.38248275, 0.66678656, 0.24662114, 0.37217159, 0.51131479],
       [0.82161554, 0.71185664, 0.44522448, 0.72819607, 0.50784429],
       [0.14885313, 0.63748732, 0.66702022, 0.56029545, 0.86246128],
       [0.44781909, 0.98666298, 0.70767264, 0.68352833, 0.47911015],
       [0.74417962, 0.64361053, 0.1896956 , 0.04794555, 0.57195855]])

In [25]:
# Guarian distro or Standard distro
np.random.randn(2)

array([ 0.44814187, -0.45367958])

In [26]:
np.random.randn(4,4)

array([[-0.85940293, -1.37780984,  0.0573281 ,  0.93052169],
       [ 1.30118493,  0.51117086,  0.54569429, -0.35131104],
       [-0.95787245, -0.65952247,  0.50731148,  0.3182646 ],
       [ 0.36293161,  0.56472384, -0.39689186, -0.48304772]])

In [27]:
# Random intagers from low o high number
np.random.randint(0, 100)

19

In [29]:
np.random.randint(0, 100,10)

array([76,  8, 14, 89, 91, 58, 39, 43, 66, 61])

In [32]:
np.random.randint(0, 100, (10,10))

array([[87, 77, 25, 68, 48, 90, 23, 77, 52, 95],
       [50, 44, 66, 48, 31, 34, 46, 12, 14, 36],
       [ 9, 49, 47, 10, 72, 79, 12, 11, 81, 85],
       [78, 95, 58, 17, 29, 74, 40, 40, 87, 91],
       [74, 61, 53, 30, 42, 28, 33, 41, 34, 15],
       [39, 39, 18, 20, 56, 12,  8,  3, 18,  8],
       [33, 11, 28, 62, 89, 99, 80, 37, 64, 75],
       [52, 80, 16, 56, 14, 88, 67, 17, 25, 27],
       [78, 66, 22, 49, 79, 21, 61, 25, 98, 37],
       [39, 70, 82, 96,  3, 96, 89, 94, 38, 34]])

In [33]:
#

In [34]:
a1 = np.arange(25)

In [35]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
a2 = np.random.randint(0,50,10)

In [37]:
a2

array([ 8, 14, 26, 49,  7, 26, 38,  3, 46, 32])

In [39]:
# Change dimensions of an array
a1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
# Find max or min 
a2.max()

49

In [41]:
a2.min()

3

In [44]:
print('Max is {} and argmax is {}'.format(a2.max(), a2.argmax()))

Max is 49 and argmax is 3


In [45]:
print('Min is {} and argmin is {}'.format(a2.min(), a2.argmin()))

Min is 3 and argmin is 7


In [46]:
a1x = a1.reshape(5,5)

In [49]:
a1x.shape

(5, 5)

In [50]:
a1x.dtype

dtype('int64')

In [51]:
from numpy.random import randint

In [56]:
randint(0,2000,(4,4))

array([[ 761, 1120,  467,  293],
       [1389, 1875, 1707, 1809],
       [ 563,  128,  678, 1822],
       [1608, 1781, 1406,  374]])